Add tree-invocation-order lazy engine to test build ordering.
nathanhammond/lazy-engine-testing pull request #3
Opened 2016-12-20 23:09 UTC by whastings

This adds a dummy engine for testing this change to ember-engines: https://github.com/ember-engines/ember-engines/pull/289

2016-12-20 23:33 UTC, nathanhammond requested changes
Looks good, a few tiny fixes.

2016-12-20 23:33 UTC, nathanhammond commented on lib/tree-invocation-order/addon/templates/application.hbs
> +lazy/addon/templates/application.hbs
```diff
- lazy
+ tree-invocation-order
```

2016-12-20 23:33 UTC, nathanhammond commented on lib/tree-invocation-order/package.json
> +  }
```diff
- ember-engines
- ember-ajax
+ broccoli-funnel
+ broccoli-merge-trees
+ broccoli-stew
```

2016-12-20 23:33 UTC, nathanhammond commented on lib/tree-invocation-order/addon/lazy-import-target.js
> +export default {};
Rename: `tree-invocation-order-import-target.js`

2016-12-20 23:33 UTC, nathanhammond commented on lib/tree-invocation-order/addon/routes.js
> +import importTarget from './lazy-import-target';
`import importTarget from './tree-invocation-order-import-target' ;`

2016-12-20 23:33 UTC, nathanhammond commented on lib/tree-invocation-order/addon/routes/lazy-route.js
> +export default {};
Rename: `tree-invocation-order-route.js`

2016-12-21 00:47 UTC, whastings commented
Thanks! I've made the fixes!

2016-12-21 00:55 UTC, nathanhammond approved these changes

2016-12-21 00:55 UTC, merged